"""empty message

Revision ID: 00d1fdbfcc6c
Revises: 
Create Date: 2018-04-14 16:08:23.990901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d1fdbfcc6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Episode',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=255), server_default='', nullable=False),
    sa.Column('source_stills', sa.VARCHAR(length=255), server_default='', nullable=False),
    sa.Column('source_desc', sa.TEXT(length=65535), nullable=False),
    sa.Column('deleted', sa.SMALLINT(), server_default='0', nullable=False),
    sa.Column('download_status', sa.SMALLINT(), server_default='1', nullable=False),
    sa.Column('download_num', sa.SMALLINT(), server_default='0', nullable=False),
    sa.Column('from_web', sa.INTEGER(), nullable=False),
    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('classify', sa.VARCHAR(length=255), server_default='', nullable=False),
    sa.Column('演员(声优) starring', sa.VARCHAR(length=255), server_default='', nullable=False),
    sa.Column('director', sa.VARCHAR(length=255), server_default='', nullable=False),
    sa.Column('video_num', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('year', sa.SMALLINT(), server_default='0', nullable=False),
    sa.Column('type_', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_episode_id', sa.INTEGER(), nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('source_video_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('episode_num', sa.SMALLINT(), nullable=False),
    sa.Column('from_web', sa.INTEGER(), nullable=False),
    sa.Column('source_url', sa.TEXT(length=65535), nullable=False),
    sa.Column('status', sa.SMALLINT(), server_default='1', nullable=False),
    sa.Column('deleted', sa.SMALLINT(), server_default='0', nullable=False),
    sa.Column('video_format', sa.VARCHAR(length=255), server_default='', nullable=False),
    sa.Column('size', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('width', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('height', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('duration', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('hash', sa.VARCHAR(length=255), server_default='', nullable=False),
    sa.Column('accessable', sa.SMALLINT(), server_default='1', nullable=False),
    sa.Column('download_speed', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('download_percent', sa.FLOAT(), server_default='0', nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('Episode')
    # ### end Alembic commands ###
